<h1>Lis&auml;&auml; uusi koira</h1>
<form action="" method="post">
<p>Rekisterinumero: <br>
<input type="text" name="reknro"></p>
<p>Nimi: <br>
<input type="text" name="nimi"></p>
<p>Syntynyt: <br>
<input type="text" name="syntynyt"></p>
<p>V&auml;ri: <br>
<input type="text" name="vari"></p>
<p>Is&auml;: <br>
<input type="text" name="isa"></p>
<p>Em&auml;: <br>
<input type="text" name="ema"></p>
<p>Rotu: <br>
<select name="rotu">
<option value="KKKA">karkeakarvainen kaniinim&auml;yr&auml;koira</option>
<option value="LKKA">lyhytkarvainen kaniinim&auml;yr&auml;koira</option>
<option value="PKKA">pitk&auml;karvainen kaniinim&auml;yr&auml;koira</option>
<option value="KKK">karkeakarvainen k&auml;&auml;pi&ouml;m&auml;yr&auml;koira</option>
<option value="LKK">lyhytkarvainen k&auml;&auml;pi&ouml;m&auml;yr&auml;koira</option>
<option value="PKK">pitk&auml;karvainen k&auml;&auml;pi&ouml;m&auml;yr&auml;koira</option>
<option value="KK" selected="selected">karkeakarvainen m&auml;yr&auml;koira</option>
<option value="LK">lyhytkarvainen m&auml;yr&auml;koira</option>
<option value="PK">pitk&auml;karvainen m&auml;yr&auml;koira</option>
</select>
</p>
<p>Omistaja: <br>
<input type="text" name="omistaja"></p>
<p>Koiran tila: <br>
<input type="text" name="koiran_tila"></p>
<input type="submit" value="Uusi koira">
</form>
