<!-- This page is for admin users to change or delete users -->
<h3>Muokkaa k&auml;ytt&auml;j&auml;n tietoja</h3>
<strong>(kaikki tiedot ovat pakollisia)</strong>
<br><br>
<table>
	<form action="" method="post">
	
		<tr><td>Nimi:</td><td><input type="text" name="nimi" maxlength="40" value="<?php echo $nimi; ?>"/></td></tr>
		<tr><td>Osoite:</td><td><input type="text" name="osoite" maxlength="70" value="<?php echo $osoite; ?>"/></td></tr>
		<tr><td>Puhelin:</td><td><input type="text" name="puhelinnumero" maxlength="20" value="<?php echo $puhelinnumero; ?>"/></td></tr>
		<tr><td>S&auml;hk&ouml;posti:</td><td><input type="text" name="email" maxlength="65" value="<?php echo $email; ?>"/></td></tr>
		<tr><td>K&auml;ytt&auml;j&auml;tunnus:</td><td><input type="text" name="kayttajatunnus" maxlength="10" value="<?php echo $kayttajatunnus; ?>"/></td><td>max 10 merkki&auml;</td></tr>
		<tr><td>Salasana:</td><td><input type="text" name="salasana" maxlength="50" value="<?php echo $salasana; ?>"/></td><td>max 10 merkki&auml;</td></tr>
		<tr><td>Kirjoita salasana uudelleen:</td><td><input type="text" name="salasana_toisto" maxlength="50" value="<?php echo $salasana; ?>"/></td></tr>
		<tr><td>K&auml;ytt&auml;j&auml;ryhm&auml;</td><td><input type="text" name="kayttajaryhma" value="<?php echo $kayttajaryhma; ?>"/></td></tr>
<br>
		<tr><td><input type="submit" name="nappula" value="Muuta" /></td></tr>
<tr><td><input type="submit" name="nappula" value="Poista" /></td></tr>
	</form>
</table>
<br><br><br>
<a href="<?php echo Atomik::url("index");?>">Etusivulle</a>