<!-- Start page for this application -->
<h1>JalostusUrosRekisteri</h1>
<h3>versio 1.00</h3>
<h2>Etusivu</h2>

<b>Sivulinkit</b>
<br>
<br>
<h3>
<a href="<?php echo Atomik::url("listdogs"); ?>">Koiralistaus</a><br>
<a href="<?php echo Atomik::url("adddog"); ?>">Koiran lis&auml;ys</a><br>
<a href="<?php echo Atomik::url("registration"); ?>">Rekister&ouml;ityminen</a><br>
<a href="<?php echo Atomik::url("login"); ?>">Sis&auml;&auml;nkirjautuminen</a><br>
<a href="<?php echo Atomik::url("logout"); ?>">Uloskirjautuminen</a><br>
<a href="<?php echo Atomik::url("listusers"); ?>">K&auml;ytt&auml;jien hallinta(admin)</a><br>
</h3>