<h1>JalostusUrosRekisteri</h1>
<h3>versio 0.95c</h3>
<h2>Etusivu</h2>

<b>Sivulinkit</b>
<br>
<br>

<a href="<?php echo Atomik::url("listdogs"); ?>">Koiralistaus</a><br>
<a href="<?php echo Atomik::url("adddog"); ?>">Koiran lis&auml;ys</a><br>
<a href="<?php echo Atomik::url("registration"); ?>">Rekister&ouml;ityminen</a><br>
<a href="<?php echo Atomik::url("login"); ?>">Sis&auml;&auml;nkirjautuminen</a><br>
<a href="<?php echo Atomik::url("logout"); ?>">Uloskirjautuminen</a><br>