<h1>JalostusUrosRekisteri</h1>
<h3>versio 0.95a</h3>
<h2>Etusivu</h2>

<b>Sivulinkit</b>
<br>
<br>


<a href="/?action=adddog">Koiran lis&auml;ys</a><br>
<a href="/?action=listdogs">Koiralistaus</a><br>
<a href="/?action=registration">Rekister&ouml;ityminen</a><br>
<a href="/?action=login_user">Sis&auml;&auml;nkirjautuminen</a><br>
<a href="/?action=login_admin">Sis&auml;&auml;nkirjautuminen admin</a><br>
