
<table border>
<tr><td><b>REKISTERINUMERO</b></td>
<td><b>NIMI</b></td>
<td><b>SYNTYMAAIKA</b></td>
<td><b>VARI</b></td>
<td><b>ISA</b></td>
<td><b>EMA</b></td>
<td><b>ROTU</b></td>
<td><b>OMISTAJA</b></td>
<td><b>TILA</b></td>
<td><b>LUT</b></td>
<td></td>
</tr>


<?php while ($rivi = $dogs->fetch()) {?>
   <tr>
   <td><?php echo $rivi["reknro"];?></td>
   <td><?php echo $rivi["nimi"];?></td>
   <td><?php echo $rivi["syntynyt"];?></td>
   <td><?php echo $rivi["vari"];?></td>
   <td><?php echo $rivi["isa"];?></td>
   <td><?php echo $rivi["ema"];?></td>
   <td><?php echo $rivi["rotu"];?></td>
   <td><?php echo $rivi["omistaja"];?></td>
   <td><?php echo $rivi["koiran_tila"];?></td>
   <td><?php echo $rivi["koetulos_lut"]; ?> </td>

   <td><a href="<?php echo Atomik::url('/editdog',array('reknro'=>$rivi["reknro"]));?>">Muokkaa</a> </td>
   </tr>
<?php }?>
</table>
<br><br><br>
<a href="http://localhost/?action=index">Etusivulle</a><br>
