<!-- Login page -->
<h3>Sis&auml;&auml;nkirjautuminen<h3>

<table>
	<form action="?action=login" method="post">

	<tr><td>K&auml;ytt&auml;j&auml;nimi:</td><td><input type="text" name="username" maxlength="10"/></td>
	<td>max 10 merkki&auml;</td></tr>
	<tr></tr>
	<tr><td>Salasana:</td><td><input type="password" name="password" maxlength="10"/></td>
	<td>max 10 merkki&auml;</td></tr>
	<tr></tr><tr></tr>
	<tr><td><input type="submit" value="L&auml;het&auml;"/><td></tr>
	<td><input type="reset";/></td>
	</tr>
	</form>
	</table>
<br><br><br>
<a href="<?php echo Atomik::url("index");?>">Etusivulle</a>
